---
variables:
  FF_NETWORK_PER_BUILD: 'true'
  PYTHON_VERSION: '3.10'

workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - validate
  - test
  - security
  - build

.pip cache:
  cache:
    paths:
      - $PIP_CACHE_DIR
    when: always
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

.security defaults:
  stage: security
  allow_failure: true
  needs: []

.test defaults:
  extends:
    - .pip cache
  image: python:$PYTHON_VERSION
  before_script:
    - apt update
    - apt install -y
        cmake
        libgirepository1.0-dev
    - pip install -r requirements-dev.txt
  needs: []

.validate defaults:
  extends:
    - .test defaults
  stage: validate
  script:
    - >-
      "${VALIDATE_TOOL}" ${VALIDATE_TOOL_ARGS}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

flake8:
  extends:
    - .validate defaults
  variables:
    VALIDATE_TOOL: flake8

isort:
  extends:
    - .validate defaults
  variables:
    VALIDATE_TOOL: isort
    VALIDATE_TOOL_ARGS: --check --diff .

black:
  extends:
    - .validate defaults
  variables:
    VALIDATE_TOOL: black
    VALIDATE_TOOL_ARGS: --check --diff .

# https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/blob/801093be0b88f23c8dbabe9cfce7134548f7ccdc/templates/ci-fairy.yml
# https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/876ca5d2de92efbea3f2379839073747c9e0dd55/.gitlab-ci.yml#L82
check commits:
  stage: validate
  image: quay.io/freedesktop.org/ci-templates:ci-fairy-sha256-eb20531b68e57da06f4e631402fd494869b1529e2c4ad05cfe24ef3fb8038815
  script:
    - ci-fairy check-commits --junit-xml=commit-message-junit-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - commit-message-junit-report.xml
    reports:
      junit: commit-message-junit-report.xml
  variables:
    GIT_DEPTH: "100"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

security (trivy):
  extends:
    - .security defaults
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy fs .
  cache:
    paths:
      - .trivy
    when: always
  variables:
    TRIVY_CACHE_DIR: .trivy
    TRIVY_EXIT_CODE: 1
    TRIVY_SCANNERS: vuln,config

security (safety):
  extends:
    - .pip cache
    - .security defaults
  image:
    name: python:$PYTHON_VERSION
  before_script:
    - pip install safety
  script:
    - safety check -r requirements-dev.txt

security (pip-audit):
  extends:
    - .pip cache
    - .security defaults
  image:
    name: python:$PYTHON_VERSION
  before_script:
    - pip install pip-audit
    - apt update
    - apt install -y
        cmake
        libgirepository1.0-dev
  script:
    - pip-audit -r requirements-dev.txt

build:
  stage: build
  image: python:$PYTHON_VERSION
  before_script:
    - apt-get update
    - apt-get install -y libgirepository1.0-dev ninja-build
    - pip install meson pygobject
  script:
    - meson --prefix=/usr builddir
    - cd builddir
    - meson install
  parallel:
    matrix:
      - PYTHON_VERSION:
        - '3.10'
        - '3.11'
        - '3.12'
